name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5195bdda46f40fc2fe8af82f32c21f2d7b9b1e6134de029af2089f7341002708"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
