name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb124eaec1bcacc8e6c17978210a963dd9cbb9bfac3c63c326bc52b2938d5513"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
