name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b1fe863ceba3ad89a6cb44948cb36b477e6e75ab90faea5ab4912b6f2854395"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
